language: php

git:
  depth: 1

cache:
  directories:
    - $HOME/.composer/cache

sudo: false

env:
  global:
    - COMPOSER_ALLOW_XDEBUG=0

matrix:
  include:
    - php: 5.6
      env: COMPOSER_COMMAND=install
    - php: 7.0
      env: COMPOSER_COMMAND=update
    - php: 7.1
      env: COMPOSER_COMMAND=update
    - php: 7.2
      env: COMPOSER_COMMAND=update
  fast_finish: true

install:
  - composer $COMPOSER_COMMAND --no-interaction

script:
  - php vendor/bin/security-checker security:check --end-point=http://security.sensiolabs.org/check_lock
